export const actsOfKindness = [
	"Send a positive message to someone you care about.",
	"Help a neighbor with a task or errand.",
	"Donate to a charity of your choice.",
	"Volunteer at a local shelter.",
	"Buy a coffee for a stranger.",
	"Compliment someone.",
	"Write a thank you note to a friend.",
	"Cook a meal for your family.",
	"Offer to babysit for a friend.",
	"Plant a tree.",
	"Clean up a public space.",
	"Donate blood.",
	"Help someone with their groceries.",
	"Hold the door open for someone.",
	"Let someone go ahead of you in line.",
	"Donate clothes you no longer wear.",
	"Write a positive online review for a small business.",
	"Send a care package to a soldier overseas.",
	"Donate books to a library.",
	"Offer to walk a neighbor's dog.",
	"Leave a generous tip for a server.",
	"Donate food to a food bank.",
	"Offer to help a coworker with a project.",
	"Pay for someone's parking meter.",
	"Donate school supplies to a school.",
	"Send flowers to a nursing home.",
	"Offer to run errands for an elderly neighbor.",
	"Donate toys to a children's hospital.",
	"Leave a positive note in a library book.",
	"Give up your seat on public transport.",
	"Donate your old laptop to someone in need.",
	"Teach someone a new skill.",
	"Donate your hair to a charity that makes wigs for cancer patients.",
	"Sponsor a child's education.",
	"Start a community garden.",
	"Donate your old glasses to an organization that recycles them for people in need.",
	"Organize a charity event in your community.",
	"Donate your skills to a non-profit organization.",
	"Help a friend with a DIY project.",
	"Donate a percentage of your income to charity.",
	"Start a free library in your neighborhood.",
	"Sponsor a local sports team.",
	"Donate your old car to a charity.",
	"Help a friend move house.",
	"Donate your old furniture to a family in need.",
	"Help a friend paint their house.",
	"Donate your old bicycle to a charity.",
	"Help a friend with gardening.",
	"Donate your old textbooks to a school.",
	"Help a friend with their resume.",
	"Donate your old musical instruments to a school.",
	"Help a friend practice for a job interview.",
	"Donate your old clothes to a homeless shelter.",
	"Create a bird feeder for your garden.",
	"Offer to help a friend with house cleaning.",
	"Make a homemade gift for someone.",
	"Offer to mow your neighbor's lawn.",
	"Leave a kind note for your mail carrier.",
	"Make a donation to a charity of your choice.",
	"Offer to help a friend with their homework.",
	"Make a meal for a homeless person.",
	"Offer to help a friend with their yard sale.",
	"Make a homemade card for a friend.",
	"Offer to help a friend with their car wash.",
	"Make a homemade cake for a neighbor.",
	"Offer to help a friend with their garage cleaning.",
	"Make a homemade gift basket for a friend.",
	"Offer to help a friend with their pet sitting.",
	"Make a homemade soup for a sick friend.",
	"Offer to help a friend with their laundry.",
	"Make a homemade candle for a friend.",
	"Offer to help a friend with their grocery shopping.",
	"Make a homemade scarf for a friend.",
	"Offer to help a friend with their home renovation.",
	"Make a homemade blanket for a friend.",
	"Offer to help a friend with their home decoration.",
	"Make a homemade ornament for a friend.",
	"Offer to help a friend with their home repair."
];